name: tc1d-binder
channels:
  - conda-forge
dependencies:
  - corner
  - emcee
  - matplotlib
  - neighpy
  - numpy
  - python>=3.10
  - schwimmbad
  - scikit-learn
  - scipy
  - pip
  - pip:
    - tc1d